---
#!/usr/bin/env ansible-playbook
# vim:ft=ansible:
- hosts: localhost
  connection: local
  become: True
  gather_facts: True
  serial: 1
  roles:
    - ansible-role-docker
    - ansible-role-ssl
    - ansible-nexus
    - ansible-nginx
