---
- name: Check if Jenkins Image exists
  shell: docker image ls
  register: check_result
- debug:
    var: check_result.stdout

- name: pull Jenkins image from Dockerhub
  shell: "docker pull jenkins/jenkins"
  when: check_result.changed
  register: image_result
- debug:
    var: image_result

- name: Run Jenkins container
  shell: "sudo docker run --name jenkins -p 8080:8080 -p 50000:50000 jenkins/jenkins &"
  register: image_run
- debug:
    var: image_run

- name: sleep for 60 seconds and continue with play
  wait_for:
    timeout: 60
  delegate_to: localhost

- name: Restart Jenkins container
  shell: "docker start jenkins"
  register: start_result
- debug:
    var: start_result

- name: Get temp password for Jenkins 
  shell: "docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword"
  register: pass_result
- debug:
    var: pass_result.stdout

- name: Create temp pass file for Jenkins
  template:
    src: jenkins-pass.j2
    dest: ./jenkins-pass
