---
- name: Check if Jenkins Image exists
  shell: docker image ls
  register: check
- debug:
    var: check.stdout

- name: pull Jenkins image from Dockerhub
  shell: docker pull jenkinsci/jenkins
  when: check.changed
  register: image
- debug:
    var: image

- name: Run Jenkins container
  shell: sudo docker run --name jenkins -p 8080:8080 -p 50000:50000 docker.io/jenkinsci/jenkins &
  register: image_run
- debug:
    var: image_run


- name: sleep for 20 seconds and continue with play
  wait_for:
    timeout: 20
  delegate_to: localhost

- name: Get temp password for Jenkins 
  shell: docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword
  register: pass
- debug:
    var: pass.stdout
